name: AhoyPurge
main: uk.co.ahoyworld.AhoyPurge
version: 0.1crap

commands:
  hide:
    description: Turns the admin invisible.
    usage: /hide or /show
    permission: ahoypurge.hide
    permission-message: Nothing to see here.